/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as EmBreveRouteImport } from './routes/em-breve'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as AuthContaRouteImport } from './routes/_auth/conta'
import { Route as AuthPagamentoRouteImport } from './routes/_auth/pagamento'
import { Route as NftNftIdRouteImport } from './routes/nft.$nftId'
import { Route as AuthContaIndexRouteImport } from './routes/_auth/conta/index'
import { Route as AuthContaAtividadeRouteImport } from './routes/_auth/conta/atividade'
import { Route as AuthContaCarteirasRouteImport } from './routes/_auth/conta/carteiras'
import { Route as AuthContaFavoritosRouteImport } from './routes/_auth/conta/favoritos'
import { Route as AuthContaPerfilRouteImport } from './routes/_auth/conta/perfil'
import { Route as AuthPedidosOrderIdRouteImport } from './routes/_auth/pedidos.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveRoute = EmBreveRouteImport.update({
  id: '/em-breve',
  path: '/em-breve',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthContaRoute = AuthContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagamentoRoute = AuthPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AuthRoute,
} as any)
const NftNftIdRoute = NftNftIdRouteImport.update({
  id: '/nft/$nftId',
  path: '/nft/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthContaIndexRoute = AuthContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthContaRoute,
} as any)
const AuthContaAtividadeRoute = AuthContaAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AuthContaRoute,
} as any)
const AuthContaCarteirasRoute = AuthContaCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => AuthContaRoute,
} as any)
const AuthContaFavoritosRoute = AuthContaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthContaRoute,
} as any)
const AuthContaPerfilRoute = AuthContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthContaRoute,
} as any)
const AuthPedidosOrderIdRoute = AuthPedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/em-breve': typeof EmBreveRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/conta': typeof AuthContaRouteWithChildren
  '/pagamento': typeof AuthPagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/conta/atividade': typeof AuthContaAtividadeRoute
  '/conta/carteiras': typeof AuthContaCarteirasRoute
  '/conta/favoritos': typeof AuthContaFavoritosRoute
  '/conta/perfil': typeof AuthContaPerfilRoute
  '/pedidos/$orderId': typeof AuthPedidosOrderIdRoute
  '/conta/': typeof AuthContaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/em-breve': typeof EmBreveRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof AuthPagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/conta/atividade': typeof AuthContaAtividadeRoute
  '/conta/carteiras': typeof AuthContaCarteirasRoute
  '/conta/favoritos': typeof AuthContaFavoritosRoute
  '/conta/perfil': typeof AuthContaPerfilRoute
  '/pedidos/$orderId': typeof AuthPedidosOrderIdRoute
  '/conta': typeof AuthContaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/em-breve': typeof EmBreveRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/_auth/conta': typeof AuthContaRouteWithChildren
  '/_auth/pagamento': typeof AuthPagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/_auth/conta/atividade': typeof AuthContaAtividadeRoute
  '/_auth/conta/carteiras': typeof AuthContaCarteirasRoute
  '/_auth/conta/favoritos': typeof AuthContaFavoritosRoute
  '/_auth/conta/perfil': typeof AuthContaPerfilRoute
  '/_auth/pedidos/$orderId': typeof AuthPedidosOrderIdRoute
  '/_auth/conta/': typeof AuthContaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/em-breve'
    | '/entrar'
    | '/mercado'
    | '/conta'
    | '/pagamento'
    | '/nft/$nftId'
    | '/conta/atividade'
    | '/conta/carteiras'
    | '/conta/favoritos'
    | '/conta/perfil'
    | '/pedidos/$orderId'
    | '/conta/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/em-breve'
    | '/entrar'
    | '/mercado'
    | '/pagamento'
    | '/nft/$nftId'
    | '/conta/atividade'
    | '/conta/carteiras'
    | '/conta/favoritos'
    | '/conta/perfil'
    | '/pedidos/$orderId'
    | '/conta'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/cadastro'
    | '/carrinho'
    | '/em-breve'
    | '/entrar'
    | '/mercado'
    | '/_auth/conta'
    | '/_auth/pagamento'
    | '/nft/$nftId'
    | '/_auth/conta/atividade'
    | '/_auth/conta/carteiras'
    | '/_auth/conta/favoritos'
    | '/_auth/conta/perfil'
    | '/_auth/pedidos/$orderId'
    | '/_auth/conta/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  EmBreveRoute: typeof EmBreveRoute
  EntrarRoute: typeof EntrarRoute
  MercadoRoute: typeof MercadoRoute
  NftNftIdRoute: typeof NftNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve': {
      id: '/em-breve'
      path: '/em-breve'
      fullPath: '/em-breve'
      preLoaderRoute: typeof EmBreveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/conta': {
      id: '/_auth/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthContaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pagamento': {
      id: '/_auth/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof AuthPagamentoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/nft/$nftId': {
      id: '/nft/$nftId'
      path: '/nft/$nftId'
      fullPath: '/nft/$nftId'
      preLoaderRoute: typeof NftNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/conta/': {
      id: '/_auth/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof AuthContaIndexRouteImport
      parentRoute: typeof AuthContaRoute
    }
    '/_auth/conta/atividade': {
      id: '/_auth/conta/atividade'
      path: '/atividade'
      fullPath: '/conta/atividade'
      preLoaderRoute: typeof AuthContaAtividadeRouteImport
      parentRoute: typeof AuthContaRoute
    }
    '/_auth/conta/carteiras': {
      id: '/_auth/conta/carteiras'
      path: '/carteiras'
      fullPath: '/conta/carteiras'
      preLoaderRoute: typeof AuthContaCarteirasRouteImport
      parentRoute: typeof AuthContaRoute
    }
    '/_auth/conta/favoritos': {
      id: '/_auth/conta/favoritos'
      path: '/favoritos'
      fullPath: '/conta/favoritos'
      preLoaderRoute: typeof AuthContaFavoritosRouteImport
      parentRoute: typeof AuthContaRoute
    }
    '/_auth/conta/perfil': {
      id: '/_auth/conta/perfil'
      path: '/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof AuthContaPerfilRouteImport
      parentRoute: typeof AuthContaRoute
    }
    '/_auth/pedidos/$orderId': {
      id: '/_auth/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthPedidosOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthContaRouteChildren {
  AuthContaAtividadeRoute: typeof AuthContaAtividadeRoute
  AuthContaCarteirasRoute: typeof AuthContaCarteirasRoute
  AuthContaFavoritosRoute: typeof AuthContaFavoritosRoute
  AuthContaPerfilRoute: typeof AuthContaPerfilRoute
  AuthContaIndexRoute: typeof AuthContaIndexRoute
}

const AuthContaRouteChildren: AuthContaRouteChildren = {
  AuthContaAtividadeRoute: AuthContaAtividadeRoute,
  AuthContaCarteirasRoute: AuthContaCarteirasRoute,
  AuthContaFavoritosRoute: AuthContaFavoritosRoute,
  AuthContaPerfilRoute: AuthContaPerfilRoute,
  AuthContaIndexRoute: AuthContaIndexRoute,
}

const AuthContaRouteWithChildren = AuthContaRoute._addFileChildren(
  AuthContaRouteChildren,
)

interface AuthRouteChildren {
  AuthContaRoute: typeof AuthContaRouteWithChildren
  AuthPagamentoRoute: typeof AuthPagamentoRoute
  AuthPedidosOrderIdRoute: typeof AuthPedidosOrderIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthContaRoute: AuthContaRouteWithChildren,
  AuthPagamentoRoute: AuthPagamentoRoute,
  AuthPedidosOrderIdRoute: AuthPedidosOrderIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  EmBreveRoute: EmBreveRoute,
  EntrarRoute: EntrarRoute,
  MercadoRoute: MercadoRoute,
  NftNftIdRoute: NftNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
